# FILL THIS UP
path: '/home/ychau001/driving_data/64x64_34_0' # path to dataset folder
classes: 3 # number of classes in the dataset
num_workers: 8 # number of cpu cores used

batch_size: 512
image_width: 64
image_height: 64
mean:
  - 0
  - 0
  - 0
std_dev:
  - 1
  - 1
  - 1

# Augmentation Strategies

probability_cutmix: 0. # Float (0->1.), set to 0 to off cutmix
alpha_cutmix: 0.
weighted_sampling: 1
train_transform:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: ${datamodule.image_height}
      width: ${datamodule.image_width}
      interpolation: 2
    - _target_: albumentations.Normalize
      mean: ${datamodule.mean}
      std: ${datamodule.std_dev}
    - _target_: albumentations.pytorch.ToTensorV2
test_transform:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: ${datamodule.image_height}
      width: ${datamodule.image_width}
      interpolation: 2
    - _target_: albumentations.Normalize
      mean: ${datamodule.mean}
      std: ${datamodule.std_dev}
    - _target_: albumentations.pytorch.ToTensorV2
