# FILL THIS UP
dataset_path: '/home/ychau001/driving_data/64x64_34_0/val'

architecture: fcnn # if auto, take from models/architecture
checkpoint: '/home/ychau001/vision_backbones/logs/fcnn_64_0.75/best.ckpt' # if auto, use pretrained weights from timm
classes: 3 # if auto, use classes from datamodule/classes
trt_opt: false # tensorrt optimization
batch_size: 1 # only batch_size=1 works for trt_opt
measure_speed: false # calc speed in ms
num_samples: 100 # num_samples to average out when calculating inference speed
fp16_mode: true

test_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size:
        # - ${datamodule.image_height}
        # - ${datamodule.image_width}
        - 64
        - 64
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: ${datamodule.mean}
      std: ${datamodule.std_dev}
      inplace: true
    - _target_: torchvision.transforms.Grayscale
      num_output_channels: 1
