# FILL THIS UP
dataset_path:

architecture: "auto" # if auto, take from models/architecture
checkpoint: "auto" # if auto, use pretrained weights from timm
classes: 1000 # if auto, use classes from datamodule/classes
trt_opt: true # tensorrt optimization
batch_size: 1 # only batch_size=1 works for trt_opt
measure_speed: true # calc speed in ms
num_samples: 1000 # num_samples to average out when calculating inference speed
fp16_mode: false

test_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size:
        - ${datamodule.image_height}
        - ${datamodule.image_width}
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: ${datamodule.mean}
      std: ${datamodule.std_dev}
      inplace: true
