import argparse

import pandas as pd


def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--initial-benchmark-path",
        type=str,
        default="./results/full_speed_benchmark.csv",
        help="Path to CSV File Generated by benchmark.py",
    )
    parser.add_argument(
        "--speed-filter",
        type=list,
        default=["trt_speed_fp32", 2],
        help="Args for speed filter, [column_name_for_speed, max_inference_speed]",
    )
    parser.add_argument(
        "--accuracy-filter",
        type=list,
        default=["trt_top1_fp32", 5],
        help="Args for the accuracy filter, [column_name_for_accuracy, top_k]",
    )
    return parser.parse_args()


def main(opt):
    benchmark_df = pd.read_csv(opt.initial_benchmark_path)
    col, threshold = opt.speed_filter
    trt_df = benchmark_df[benchmark_df[col].notnull()]
    trt_df = trt_df[trt_df[col] < threshold]

    col, k = opt.accuracy_filter
    final = trt_df.getnlargest(k, col)

    return final[col]


if __name__ == "__main__":

    opt = parse_opt()
    final = main(opt)
    print(final)
